config/routes.rb
Rails.application.routes.draw do
 
  get "users/sign_in"
  get "mains/index"
  get "users/logout"
  get "homepages/coba"
  post "users/login"
  resources :users do
    collection do
      get :create_mobile
      get :login_mobile
    end
  end
  resources :babysitters do 
    collection do
      get :update_rate
      post :create_mobile
    end
  end
  get "parents/get_user", to: "parents#get_user"
  resources :parents
  root "homepages#index"
  get 'admins/index'
  get 'homepages/frame' 
  post "homepages/copas"
  post '/rate' => 'rater#create', as: 'rate'
  namespace :admins do
    resources :graphs
    resources :skills
  end










end

app/models/babysitter.rb
class Babysitter < ActiveRecord::Base

	belongs_to :user 
	has_and_belongs_to_many :skills, join_table: "babysitter_skills", dependent: :destroy

	has_many :role_ratings, as: :cacheable
	has_many :pictures, as: :pictureable
	validates :nik , :age, :description, :price, presence: true

	ratyrate_rateable "quality"	, "original_score"
	
end

app/controllers/babysitters_controller.rb
class BabysittersController < ApplicationController
	before_action :current_user

	def index
		@user = current_user
		@babysitter = current_user.babysitter	
		@skills = @babysitter.skills
		@picture = Picture.find_by(pictureable_id: @babysitter.id, pictureable_type: "Babysitter")
		@parents = Ortu.all
	end

	def new
		if params[:mobile] == "true"
			@user = User.find(current_user.id)
		end
		@babysitter = current_user.babysitter.present?  ? current_user.babysitter : Babysitter.new
		@skills = Skill.all
	end

	def create
		if current_user
			params[:babysitter][:user_id] = session[:user_id]
		end

		skill_ids = params[:babysitter].delete("skill_ids")
		selected_skills = []

		selected_skills = skill_ids.collect{ |skil_id| Skill.find(skil_id) }
		@babysitter = Babysitter.new(babysitter_params)
		
		if @babysitter.save
			@babysitter.skills = selected_skills
			save_picture!(@babysitter.id, "Babysitter", params[:babysitter][:photos])
			redirect_to babysitters_path
		else
			render_to 'new'
		end
	end

	#handle create babysitter for mobile
	def create_mobile	
		unless check_params_complete_data
			flash[:warning] = "pastikan semua data telah terisi !"
			redirect_to new_babysitter_path(mobile: "true")
		end

		params[:babysitter][:user_id] = current_user.id
		price = params[:babysitter][:price]
		params[:babysitter][:price] = price.to_i / 1000
		@user = User.find(current_user)

		skill_ids = params[:babysitter].delete("skill_ids")
		selected_skills  = []
		selected_skills = skill_ids.collect{ |skill_id| Skill.find(skill_id) } unless skill_ids.blank?
		
		unless @user.update_attributes(user_params)
			render "new", mobile: "true"
		end

		@babysitter = Babysitter.new(babysitter_params)
		unless @babysitter.save
			render "new", mobile: "true"
		end

		@babysitter.skills = selected_skills unless selected_skills.blank?
		save_picture!(@babysitter.id, "Babysitter", params[:babysitter][:picture_url])
		redirect_to babysitters_path
	end

	def save_picture! (id, type, url)
		if url.present?
			params[:picture] = {}
			params[:picture][:picture_url] = url
			params[:picture][:pictureable_id] = id 
			params[:picture][:pictureable_type] = type
			@picture = Picture.new(picture_params)
			@picture.save
		end
	end

	def save_document!(id, type, url)
		if url.present?
			params[:document] = {}
			params[:document][:document_url] = url
			params[:document][:documentable_id] = id
			params[:document][:documentable_type] = type
			@document = Document.new(document_params)
			@document.save
		end
	end

	def show
		@babysitter = Babysitter.find(params[:id])
		@skills = @babysitter.skills
		@user = @babysitter.user
		@pictures = []
		pictures = @babysitter.pictures
		pictures.each do |picture|
			@pictures << {
				id: picture.id,
				pictureId: picture.pictureable_id,
				pictureType: picture.pictureable_type,
				pictureUrl: picture.picture_url.url
			}
		end
		respond_to do |format|
			format.html {render :show}
			format.js do
				render :show
			end
		end
	end

	def edit
	@user = current_user
	@babysitter = Babysitter.find(params[:id])
	@skills = Skill.all
	# @babysitter_skills = @babysitter.skills
	
	respond_to do |format|
		format.html { render :edit }
		format.js { render "edit.js"}
	end

	end
	
	def update
		if current_user
			params[:babysitter][:user_id] = session[:user_id]
		end
		skill_ids = params[:babysitter].delete("skill_ids")
		selected_skills = skill_ids.collect{ |skil_id| Skill.find(skil_id)}
		@babysitter = Babysitter.find(params[:id])	
		
		if 	@babysitter.update_attributes(babysitter_params)
			@babysitter.skills = selected_skills
			flash[:notice]="Your baby profile has been updated"
			redirect_to babysitter_path
		else
			flash[:alert]="your baby profile failed to update"
			redirect_to edit_babysitter_path
		end
	end

	def destroy
	@babysitter = Babysitter.find(params[:id])
	@babysitter_skills = @babysitter.destroy

		if @babysitter_skills
			flash[:notice] = "babysitter profile has been deleted"
			redirect_to mains_index_path
		else
			flash[:alert] = "babysitter profiled failed to deleted"
			redirect_to babysitter_path(@babysitter)
		end
	end

	def update_rate

	end

	def check_params_complete_data
		return false if params[:user][:firstname].nil?
		return false if params[:user][:lastname].nil?
		return false if params[:user][:bornplace].nil?
		return false if params[:user][:borndate].nil?
		return false if params[:user][:gender].nil?
		return false if params[:user][:address].nil?
		return false if params[:user][:phone_number].nil?
		return false if params[:babysitter][:nik].nil? 
		return false if params[:babysitter][:picture].nil?
		return false if params[:babysitter][:skill_ids].nil?
		return false if params[:babysitter][:price].nil?
		return false if params[:babysitter][:description].nil?
		return false if params[:babysitter][:age].nil?

		return true
	end

	private
	def babysitter_params
		params.require(:babysitter).permit(:nik, :age, :description, :user_id, :skills_id, :price)
	end

	def picture_params
		params.require(:picture).permit(:picture_url, :pictureable_id, :pictureable_type)
	end

	def picture_mobile_params
		params.require(:picture).permit(:picture_url, :remote_picture_url_url, :pictureable_id, :pictureable_type)
	end

	def document_params
		params.require(:document).permit(:document_url, :documentable_id, :documentable_type)
	end

	def user_params
		params.require(:user).permit(:firstname, :lastname, :bornplace, :borndate, :gender, :address, :phone_number)
	end

end

app/helpers/babysitter_helper.rb
module BabysitterHelper

  def has_babysitter?
    @babysitter = Babysitter.find_by_user_id(session[:user_id])
    unless @babysitter
      link_to 'Create New Babysitter' , new_babysitter_path
  	else
  	  link_to "Babysitter Profile", babysitter_path(@babysitter.id)
    end

  end

  def get_babysitters
  	babysitters = Babysitter.all
	  babysitters.as_json(include: [:user, :role_ratings, :pictures], except: [:password_digest])
  end

  def get_babysitter
      babysitter = current_user.babysitter
      babysitter.as_json(include: [:user, :role_ratings], except: [:password_digest])
  end

end

app/views/babysitters/_error.html.erb
<!-- partial error message page -->
<% if @babysitter.errors.any? %>
<div class="panel panel-default">
	<div class="panel-heading">
	Warning !! <%= pluralize(@babysitter.errors.count, "error") %> happened, read below 
	</div>

	<div class="panel-body">
		<ul>
		<% @babysitter.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/babysitters/edit.html.erb
<% if params[:mobile] == "true" %>
  <%= form_for :babysitter, url: babysitter_path(@babysitter), method: :patch do |f| %>
    <%= f.file_field :picture_ur, class: "hidden" %>
    <%= react_component "BabysitterFormMobile", csrf_token: form_authenticity_token %>
  <% end %>
<% else %>
  <%= render 'error' %>
  <div class="panel panel-default">
    <div class="panel-heading">
      Babysitter Registration
    </div>
    <div class="panel-body">
      <%= form_for :babysitter, url: babysitter_path(@babysitter), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :nik , "Identity Number" %>
        <%= f.text_field :nik, placeholder: "Your Identity number", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :age, "Age" %>
        <%= f.number_field :age, placeholder: "Your Age", class: "form-control" %>
      </div>


      <div class="form-group">
        <% @skill.each do |skill| %>
        <input type="checkbox" name="babysitter[skills_ids][]" value=<%= skill.id %>
          <% @babysitter_skills.each do |b_skill| %>
            <% if b_skill.id == skill.id %>
                <%= "checked" %>
                <% break %>
            <% end %>
          <% end %>>
          <%= label_tag(skill.id, skill.name) %>
        <% end %>
      </div>



      <div class="form-group">
        <%= f.label :description , "Skill Description" %>
        <%= f.text_area :description, class: "form-control", rows: 7 %>
      </div>

      <div class="form-group">
        <%= f.label :photos, "Upload Picture" %>
          <%= f.file_field :photos ,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-md btn-info" %>
      </div>

      <% end %>
    </div>
  </div>
<% end %>

<script>
  dispatcher.dispatch({
    actionType: "babysitter-mobile-set-user",
    attributes: <%= json_for(@user).html_safe %>  
  })

  dispatcher.dispatch({
    actionType: "babysitter-mobile-set-babysitter",
    attributes: <%= json_for(@babysitter).html_safe %>
  })

  dispatcher.dispatch({
      actionType: "babysitter-mobile-set-skills",
      skills: <%= json_for(@skills).html_safe %>
   })

  dispatcher.dispatch({
    actionType: "babysitter-change-edit-mode",
    editMode: true
  })

</script>

app/views/babysitters/index.html.erb
<script>
	dispatcher.dispatch({
		actionType: "mainpage-mobile-set-babysitter",
		user: <%= json_for(@user).html_safe %>,
		babysitter: <%= json_for(@babysitter).html_safe %>,
		parents: <%= json_for(@parents).html_safe %>
	})
</script>

<%= render "layouts/navbar" %>
<%= react_component "MainpageMobile", currentUser: current_user, csrf_token: form_authenticity_token %>
<div id="mainpage" class="mainpages">
	<div class="row">
		<div class="col-sm-2 sidebar-frame">
			<%= react_component "Sidebar", person: get_babysitter, skills: @skills, picture: @picture %>
		</div>	
		<div class="col-sm-6 thumbnail-frame">
			<%= react_component "Thumbnail", thumbs: get_thumbs, currentUser: current_user %>
		</div>
	<div class="col-sm-4">
			<%= react_component "Profile", currentUser: get_current_user %>
		</div>
	</div>
</div>

<script>
	$(".babysitter-rating").html("<%=j render 'layouts/display_babysitter_rate' %>")
</script>

app/views/babysitters/new.html.erb
<% if params[:mobile] == "true" %>
  <%= form_for :babysitter, url: create_mobile_babysitters_path do |f| %>
    <%= f.file_field :picture_ur, class: "hidden" %>
   <%= react_component "BabysitterFormMobile", csrf_token: form_authenticity_token %>
  <% end %>
<% else %>
  <%= render 'error' %>
  <div class="panel panel-default">
    <div class="panel-heading">
      Babysitter Registration
    </div>
    <div class="panel-body">
      <%= form_for :babysitter, url: babysitters_path do |f| %>
      <div class="form-group">
        <%= f.label :nik , "Identity Number" %>
        <%= f.text_field :nik, placeholder: "Your Identity number", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :age, "Age" %>
        <%= f.number_field :age, placeholder: "Your Age", class: "form-control" %>
      </div>

        <% @skills.each do |skill| %>
        <%= check_box_tag "babysitter[skill_ids][]", skill.id %>
        <%= label_tag(skill.id, skill.name) %>
        <% end %>



      <div class="form-group">
        <%= f.label :description , "Skill Description" %>
        <%= f.text_area :description, class: "form-control", rows: 7 %>
      </div>

      <div class="form-group">
        <%= f.label :price, "Harga Jasa" %>
        <%= f.number_field :price %>
      </div>

      <div class="form-group">
        <%= f.label :photos, "Upload Picture" %>
          <%= f.file_field :photos ,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-md btn-info" %>
      </div>

      <% end %>
    </div>
  </div>
<% end %>

<script >

  <% if params[:mobile] == "true" %>
    dispatcher.dispatch({
      actionType: "babysitter-mobile-set-user",
      attributes: <%= json_for(@user).html_safe %>
    })

  <% end %>

  dispatcher.dispatch({
    actionType: "babysitter-mobile-set-babysitter",
    attributes: <%= json_for(@babysitter).html_safe %>
  })
      
  dispatcher.dispatch({
    actionType: "babysitter-mobile-set-skills",
    skills: <%= json_for(@skills).html_safe %>
  })
  
</script>

app/views/babysitters/show.html.erb
<script>
	dispatcher.dispatch({
		actionType: "profile-mobile-store-set-babysitter",
		babysitter: <%= json_for(@babysitter).html_safe %>,
		currentUser: <%= json_for(current_user).html_safe %>,
	})
</script>
<% if params[:mobile] == 'true' %>
	<%= react_component "ProfileMobile", csrf_token: form_authenticity_token  %>
<% else %>
	<div class="well">
		<h2>Babysitter Profile</h2>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<% if current_user.role == "babysitter" %>
					<%= rating_for @babysitter, "quality", imdb_avg: true %>
				<% else %>
					<%= rating_for @babysitter, "quality", disable_after_rate: true %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<div class="form-group">
					<h4><strong>Identity Number :</strong></h4>
					<h5><%= @babysitter.nik %></h5>
				</div>


				<div class="form-group">
					<h4><strong>Age :</strong></h4>
					<h5><%= @babysitter.age %></h5>
				</div>

				<div class="form-group">
					<h4><strong>Description :</strong></h4>
					<h5><%= @babysitter.description %></h5>
				</div>

				<div class="form-group">
					<h4><strong>Skills :</strong></h4>
					<ul>
						<% @skills.each do |skill| %>
						<li><%= skill.name %></li>
						<% end %>
					</ul>
				</div>
			</div>

			<div class="col-md-4 text-right">
				<img style="width:250px;height:250px;" src=<%= @babysitter.pictures[0].picture_url.url %> >
			</div>
		</div>
	</div>
	<%= link_to "Update Profile" , edit_babysitter_path(@babysitter) %> <br>
	<%= link_to "Delete Profile" ,babysitter_path(@babysitter), method: :delete, data: {confirm: "Are you sure to delete your profile ?"} %> <br>
<% end %>