config/routes.rb
Rails.application.routes.draw do
 
  get "users/sign_in"
  get "mains/index"
  get "users/logout"
  get "homepages/coba"
  post "users/login"
  resources :users do
    collection do
      get :create_mobile
      get :login_mobile
    end
  end
  resources :babysitters do 
    collection do
      get :update_rate
      post :create_mobile
    end
  end
  get "parents/get_user", to: "parents#get_user"
  resources :parents
  root "homepages#index"
  get 'admins/index'
  get 'homepages/frame' 
  post "homepages/copas"
  post '/rate' => 'rater#create', as: 'rate'
  namespace :admins do
    resources :graphs
    resources :skills
  end










end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/babysitter.rb
class Babysitter < ActiveRecord::Base

	belongs_to :user 
	has_and_belongs_to_many :skills, join_table: "babysitter_skills", dependent: :destroy

	has_many :role_ratings, as: :cacheable
	has_many :pictures, as: :pictureable
	validates :nik , :age, :description, :price, presence: true

	ratyrate_rateable "quality"	, "original_score"
	
end

app/models/babysitter_skill.rb
class Babysitter_skill < ActiveRecord::Base
	
end

app/models/frame.rb
class Frame < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
end

app/models/kid.rb
class Kid < ActiveRecord::Base
	
	validates :name, :gender, :age, :description, presence: true
	belongs_to :ortu
	has_many :pictures, as: :pictureable
	
	attr_accessor :picture_child


	def picture_child
		Picture.where(pictureable_id: self.id, pictureable_type: "Kid")
	end	
end

app/models/ortu.rb
class Ortu < ActiveRecord::Base

	has_many :kids, dependent: :destroy
	has_many :pictures, as: :pictureable, dependent: :destroy
	belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :picture_url, PhotoUploader
	belongs_to :pictureable, polymorphic: true
	
end	

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role_rating.rb
class RoleRating < ActiveRecord::Base
	self.table_name = "rating_caches"
	belongs_to :cacheable, polymorphic: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_and_belongs_to_many :babysitters, join_table: "babysitter_skills"

	validates :name, :description, :score, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	ratyrate_rater
	#for field validation : field should'n be empty
	validates :email, :password, :password_confirmation, presence: true , if: :sign_up?
	validates :firstname, :lastname, :gender, :bornplace, :borndate, :address, presence: true , if: :is_mobile?
	#validation for password : confirmation must matched
	validates :password, confirmation: true
	#validation for email : email that register must uniqueness
	validates :email , uniqueness: true

	has_one :babysitter, dependent: :destroy
	has_one :ortu, dependent: :destroy
	
	has_secure_password
	
	def is_babysitter?
		self.role == "babysitter" ? true : false
	end

	def is_parent?
		self.role == "parent" ? true : false
	end

	def has_finish_account?
		if self.role == "parent"
			self.has_parent? ? "parent_finish" : "parent_not_finish"
		else
			self.has_babysitter? ? "babysitter_finish" : "babysitter_not_finish"
		end
	end

	def has_babysitter?
		self.try(:babysitter) ? true : false
	end

	def has_parent?
		self.try(:ortu) ? true : false
	end

	#for mobile
	def is_mobile?
		@is_mobile = false
	end

	def is_mobile!
		@is_mobile = true
	end

	def sign_up?
		@sign_up = false
	end

	def sign_up!
		@sign_up = true
	end

	def user_complete?
		if self.firstname.present? && self.lastname.present? && self.bornplace.present? && self.borndate.present? && self.address.present? && self.gender.present? && self.phone_number.present?
			return true
		else
			return false
		end
	end

	def has_finish_user?
		if self.role == "babysitter"
			self.user_complete? && self.has_babysitter? ? "babysitter_finish" : "babysitter_not_finish"
		elsif self.role == "parent"
			self.user_complete? && self.has_parent? ? "parent_finish" : "parent_not_finish"
		end
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_error(alert)
		return {alertLabel: alert, alertType: "error"}
	end

	def alert_notice(alert)
		return {alertLabel: alert, alertType: "notify"}
	end

	def user_email
		current_user.email
	end

	def get_thumbs
		if current_user.is_babysitter?
			get_parents
		else
			get_babysitters
		end
	end

	def main_page_url
		if current_user.is_babysitter?
			babysitters_path
		else
			parents_path
		end
	end

	def current_user
		current_user
	end

end

app/helpers/babysitter_helper.rb
module BabysitterHelper

  def has_babysitter?
    @babysitter = Babysitter.find_by_user_id(session[:user_id])
    unless @babysitter
      link_to 'Create New Babysitter' , new_babysitter_path
  	else
  	  link_to "Babysitter Profile", babysitter_path(@babysitter.id)
    end

  end

  def get_babysitters
  	babysitters = Babysitter.all
	  babysitters.as_json(include: [:user, :role_ratings, :pictures], except: [:password_digest])
  end

  def get_babysitter
      babysitter = current_user.babysitter
      babysitter.as_json(include: [:user, :role_ratings], except: [:password_digest])
  end

end

app/helpers/kid_helper.rb
module KidHelper

	def get_kids(parent_id)
		kids = Kid.where(ortu_id: parent_id)
		@kids = []
		kids.each do |kid|
			@kids << kid
		end
		return @kids.as_json(include: :picture_child)
	end

end

app/helpers/parent_helper.rb
module ParentHelper

	def has_parent?
		@parents = Ortu.find_by_user_id(session[:user_id])
		unless @parents
			link_to 'Create Parent Profile', new_parent_path
		else
			link_to 'Parent Profile', parent_path(@parents)
		end
	end 

	def get_parents
		parents = Ortu.all
		parents.as_json( except: [:password_digest], include: [:user, :pictures])
	end

	def get_parent
		current_user.ortu.as_json(include: [:kids, :user])
	end

end

app/helpers/skill_helper.rb
module SkillHelper
	def current_skill
		Skill.all
	end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def get_current_user
		current_user.as_json(except: :password_digest)
	end	
end

app/views/admins/index.html.erb
<div>Admin page</div>
<%= link_to "Add Skills", new_admins_skill_path %>

app/views/layouts/_display_babysitter_rate.html.erb
<%= rating_for @babysitter, "quality", disable_after_rate: true, imdb_avg: true %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Bibibebi", main_page_url , class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
    	<li class="dropdown">
    		<a href="dropdown-toggle" data-toggle="dropdown"><%= user_email %><b class="caret"></b></a>
    		<ul class="dropdown-menu">
    			<li><%= link_to "Log-out", users_logout_path %></li>
    		</ul>
    	</li>
    </ul>
  </div>
</nav>

app/views/layouts/_rate_babysitter.html.erb
<%= rating_for @babysitter, "quality", disable_after_rate: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes"
  <%= favicon_link_tag '/favicon.png' %>
  <title>Bibibebi®</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<meta name="viewport" content="width=device-width, initial-scale=1.0" >
	<% if flash[:alert] %>
		<% flashAlert = alert_error(flash[:alert]) %>
	<% elsif flash[:notice] %>
		<% flashAlert = alert_notice(flash[:notice]) %>
	<% end %>
	<%= react_component "AlertApp" , flashAlert:flashAlert %>
	<%= yield %>
</body>
</html>